# lightning.pytorch==2.5.1.post0
experiment_name: thesis_simple_res_rnn
seed_everything: 42

trainer:
  max_epochs: 10

model:
  class_path: brf_lightning.models.BearingFaultClassifier
  init_args:
    backbone:
      class_path: brf_lightning.models.backbones.simple_brf.SimpleResRNN
      init_args:
        input_size: 1
        hidden_size: 16
        output_size: 3
        pruning: true
        adaptive_omega_a: 5000.0
        adaptive_omega_b: 8000.0
        adaptive_b_offset_a: 100.0
        adaptive_b_offset_b: 150.0
        out_adaptive_tau_mem_mean: 640.0
        out_adaptive_tau_mem_std: 160.0
        n_last: 1
        mask_prob: 0.0
        sub_seq_length: 0
        hidden_bias: false
        output_bias: false
        label_last: false
        dt: 0.0001220703125
        theta: 1.3
    num_classes: 3
    reduction: last
    criterion: null
    implicit_normal: false

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.1

lr_scheduler:
  class_path: torch.optim.lr_scheduler.LinearLR
  init_args:
    total_iters: ${trainer.max_epochs}

data:
  class_path: brf_lightning.data.BearingDataModule
  init_args:
    filepaths:
      - data/bearing_thl_v1/fAII10.csv
      - data/bearing_thl_v1/fAII20.csv
      - data/bearing_thl_v1/fAII30.csv
      - data/bearing_thl_v1/n10.csv
      - data/bearing_thl_v1/n20.csv
      - data/bearing_thl_v1/n30.csv
      - data/bearing_thl_v1/fIII10.csv
      - data/bearing_thl_v1/fIII20.csv
      - data/bearing_thl_v1/fIII30.csv
    split_strategy: chronological
    val_ratio: 0.10
    test_ratio: 0.10
    keep_fraction: 0.01

    order_domain_mode: none
    window_size: 1.0
    hop_size: 0.0
    norm: global
    target_rms: 800
    balance_mode: global_min
    num_workers: 8
    batch_size: 32
