# lightning.pytorch==2.5.1.post0
experiment_name: base
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: results/
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: '{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
        save_top_k: 1
        monitor: 'val_loss'
        mode: 'min'
  fast_dev_run: false
  max_epochs: 400
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 10
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  inference_mode: true
  use_distributed_sampler: true