# lightning.pytorch==2.5.1.post0
experiment_name: bearing_brf_stacked
seed_everything: 42

trainer:
  max_epochs: 30

model:
  class_path: brf_lightning.models.BearingFaultClassifier
  init_args:
    num_classes: 3
    reduction: last
    implicit_normal: true
    backbone:
      class_path: brf_lightning.models.backbones.BRFStackedEncoder
      init_args:
        input_size: 1
        num_classes: 2
        fs: 8192.0
        q_carrier: 10.0
        q_brfc2: 2.0
        carrier_band_hz: [1200.0, 1800.0, 2400.0]
        fault_orders: [3.05, 6.1, 9,15, 4.95, 3.95, 5.95]
        readout_tau_mean: 3.0
        readout_tau_std: 0.5
        normalize_input: true

optimizer:
  class_path: torch.optim.Adam        
  init_args:
    lr: 1.0e-2

lr_scheduler:
  class_path: torch.optim.lr_scheduler.LinearLR
  init_args:
    total_iters: ${trainer.max_epochs}

data:
  class_path: brf_lightning.data.BearingDataModule
  init_args:
    filepaths:
      - data/bearing_thl_v1/fAII10.csv
      - data/bearing_thl_v1/fAII20.csv
      - data/bearing_thl_v1/fAII30.csv
      - data/bearing_thl_v1/n10.csv
      - data/bearing_thl_v1/n20.csv
      - data/bearing_thl_v1/n30.csv
      - data/bearing_thl_v1/fIII10.csv
      - data/bearing_thl_v1/fIII20.csv
      - data/bearing_thl_v1/fIII30.csv
    split_strategy: chronological
    val_ratio: 0.10
    test_ratio: 0.10
    keep_fraction: 0.01

    # Order-domain preprocessing
    order_domain_mode: none
    window_size: 1.0                   # seconds
    hop_size: 0.30                     # 30% overlap

    norm: global
    balance_mode: global_min
    num_workers: 8
    batch_size: 32
